### PR TITLE
Fix strict mode errors from typings

### LINKED ISSUE #562: TypeScript compilation errors with v1.1.0
After updating to v1.1.0 of chartjs-plugin-zoom I can't build my typescript project because I get the following errors:

```
Error: node_modules/chartjs-plugin-zoom/types/index.d.ts:50:30 - error TS7006: Parameter 'chart' implicitly has an 'any' type.

50 export function getZoomLevel(chart): number;
                                ~~~~~


Error: node_modules/chartjs-plugin-zoom/types/options.d.ts:173:3 - error TS2411: Property 'x' of type 'ScaleLimits | undefined' is not assignable to string index type 'ScaleLimits'.

173   x?: ScaleLimits;
      ~


Error: node_modules/chartjs-plugin-zoom/types/options.d.ts:174:3 - error TS2411: Property 'y' of type 'ScaleLimits | undefined' is not assignable to string index type 'ScaleLimits'.

174   y?: ScaleLimits;
      ~



[ERROR] An error occurred while running subprocess ng.

        ng.cmd run app:build:production exited with exit code 1.
```

My version of Chart.js is v3.4.0

### PR DESCRIPTION
**Pull request by kurkle**
Resolves #562

### CODE REVIEW

File: types/options.d.ts [hunk 1]
```diff
@@ -170,8 +170,8 @@ export interface ScaleLimits {
 
 export interface LimitOptions {
   // Default horizontal and vertical scale limits
-  x?: ScaleLimits;
-  y?: ScaleLimits;
+  // x?: ScaleLimits;
```
Comment (etimberg) [inline types/options.d.ts:173]: should these be deleted instead of commented?

**Review by etimberg — APPROVED** [review]

**Review by hardmaster92 — APPROVED** [review]

**Review by etimberg — APPROVED** [review]
