### ISSUE TITLE
Chart.js 3.4.0 not working with Chartjs-Plugin-Zoom 1.0.1

### ISSUE THREAD

**Issue by rkp8** [chartjs/chartjs-plugin-zoom#579]
Using Chartjs-Plugin-Zoom 1.0.1 with Chart.js 3.4.0 gives following compile errors:

      -1 import { Plugin, ChartType, Chart, Scale, UpdateMode } from 'chart.js';
                                                  ~~~~~~~~~~
      Error: node_modules/chartjs-plugin-zoom/types/index.d.ts:1:10 - error TS2305: Module '"../../../types/chart.js"' has no exported member 'Plugin'.
      

      -1 import { Plugin, ChartType, Chart, Scale, UpdateMode } from 'chart.js';
                 ~~~~~~
      

      Error: node_modules/chartjs-plugin-zoom/types/index.d.ts:1:36 - error TS2305: Module '"../../../types/chart.js"' has no exported member 'Scale'.
      
      
      -1 import { Plugin, ChartType, Chart, Scale, UpdateMode } from 'chart.js';
      
  There are also similar errors for UpdateMode, ChartRegistry and Color.

Please let me know how to resolve this issue.

**Comment by kurkle** [comment]
Probably just `npm uninstall @types/chart.js`

**Comment by rkp8** [comment]
Tried this and confirmed that there is no @types/chart.js in node_modules. However, the error still occurs.

**Comment by rkp8** [comment]
Here is where the error occurs inside the index.d.ts of chartjs-plugin-zoom:
![Screenshot (77)](https://user-images.githubusercontent.com/60204834/130507307-82d10265-e199-473b-b0a6-2f36df59d10b.png)
