### ISSUE TITLE
Chart.js 3.0 & Angular

### ISSUE THREAD

**Issue by Nico-DF** [chartjs/chartjs-plugin-zoom#446]
Hi, 

I'm currently working on an integration of Chart.js and the zoom plugin on an angular project, and everything was working fine with 2.9.4 & 0.7.7 respectively.

**Working code on Chart.js 2.9.4**
```
import { Chart, ChartData, ChartOptions, ChartPoint } from 'chart.js';
import 'chartjs-plugin-zoom';

{some code}

options: {
  plugins: {
    zoom: {
      pan: {
        enabled: true,
        mode: 'x',
        rangeMin: { x: 0 },
        rangeMax: { x: 100 }
      },
      zoom: {
        enabled: true,
        mode: 'x',
        rangeMin: { x: 0 },
        rangeMax: { x: 100 }
      }
    }
  }
}
```
And it worked quite fine.

As it appears that Chart recently officially launched v3, I tried to upgrade it as well, as it is way better integrated with typescript than the v2 (no need for a @type import, etc.)

But there were a few hiccups during integration with plugin (I know it's still in beta).
I've seen on JS files that the registration seems ok (`chart_js.Chart.register(zoomPlugin);`), but to in fact have it to work properly I had to also register it on my side:

**Working code on Chart.js 3.0.2**
```
import { Chart, ChartData, ChartDataset, ChartOptions, registerables } from 'chart.js';
import * as ChartZoomPlugin from 'chartjs-plugin-zoom';

Chart.register(...registerables, ChartZoomPlugin.Zoom);

{some code}

options: {
  plugins: {
    zoom: {
      pan: {
        enabled: true,
        mode: 'x',
        rangeMin: { x: 0 },
        rangeMax: { x: 100 }
      },
      zoom: {
        enabled: true,
        mode: 'x',
        rangeMin: { x: 0 },
        rangeMax: { x: 100 }
      }
    }
  }
}
```

Is it really the intended use/workaround to make it work in a Typescript way? The register part I mean

**Comment by aanilyildiz** [comment]
Hi I'm currently having trouble registering this plugin on Angular 11. When I register the plugin like you it gives me compilation errors saying zoom doesn't exist on options object. How did you bypassed that error?

**Comment by Nico-DF** [comment]
> Hi I'm currently having trouble registering this plugin on Angular 11. When I register the plugin like you it gives me compilation errors saying zoom doesn't exist on options object. How did you bypassed that error?

What I basically did was:
- To use Chartjs@3.1.0 and plugin @1.0.0-beta.1 (what is essentially in my package.json)
- To have the Chart.register(...registerables, ChartZoomPlugin.Zoom); instruction above my exported class that performs the new Chart(..) (maybe not the best place)

And I don't particularly remember doing anything else

**Comment by aanilyildiz** [comment]
I managed to bypass the error using @ts-ignore. Still, thanks for the help

**Comment by Nico-DF** [comment]
Oh you meant that kind of error, yes my bad a ts-ignore on import is needed

**Comment by kurkle** [comment]
The actual error could be helpful in resolving it :)

**Comment by aanilyildiz** [comment]
`plugins: {
    // @ts-ignore
    zoom: {
        zoom: {
            enabled: true,
            drag: true,
            mode: 'xy',
        }
    }
},`

Adding the above code under options gives the following error

`Type '{ zoom: { zoom: { enabled: true; drag: true; mode: string; }; }; }' is not assignable to type '_DeepPartialObject<PluginOptionsByType<"line">>'.`

**Comment by Nico-DF** [comment]
On my case, by construction, I have no particular issue with this:

```typescript
public static buildChartOptions(
    xLabel: string,
    yLabel: string,
    minX: number,
    maxX: number,
    zoomCallback: () => void
  ): ChartOptions {
    return {
      // We are using objects like {x: 10, y: 20}, disabling parsing for performance
      parsing: false,
      // Data are already ordered
      normalized: true,
      animation: false,
      responsive: false,
      scales: {
        y: {
          title: {
            display: true,
            text: yLabel
          },
          type: 'linear',
          ticks: {
            minRotation: 50,
            maxRotation: 50
          }
        },
        x: {
          title: {
            display: true,
            text: xLabel
          },
          type: 'linear',
          min: minX,
          max: maxX,
          ticks: {
            minRotation: 50,
            maxRotation: 50
          }
        }
      },
      plugins: {
        decimation: {
          enabled: true,
          // @ts-ignore
          algorithm: 'lttb'
        },
        legend: {
          align: 'start'
        },
        zoom: {
          pan: {
            enabled: true,
            mode: 'x',
            rangeMin: {
              x: minX
            },
            rangeMax: {
              x: maxX
            }
          },
          zoom: {
            enabled: true,
            mode: 'x',
            rangeMin: {
              x: minX
            },
            rangeMax: {
              x: maxX
            },
            onZoom: zoomCallback
          }
        },
        tooltip: {
          mode: 'index',
          intersect: false
        }
      }
    };
  }
```

But my main problem was the need to do 
```typescript
// @ts-ignore
import * as ChartZoomPlugin from 'chartjs-plugin-zoom';

Chart.register(...registerables, ChartZoomPlugin.Zoom);
```

Ignore is needed for: TS7016: Could not find a declaration file for module 'chartjs-plugin-zoom'. node_modules/chartjs-plugin-zoom/dist/chartjs-plugin-zoom.js' implicitly has an 'any' type.   Try `npm install @types/chartjs-plugin-zoom` if it exists or add a new declaration (.d.ts) file containing `declare module 'chartjs-plugin-zoom';`

But the register is performed on the plugin javascript code, so something (or me) seems to be missing something

**Comment by kurkle** [comment]
> But the register is performed on the plugin javascript code, so something (or me) seems to be missing something

Its only done for the UMD build, but not ESM which you are using with `import`.

**Comment by Nico-DF** [comment]
I'm OK for the import as it is now specified in documentation.

I still update this issue thread with new error encountered when using the beta.2 and importing the plugin without any ts-ignore and strict validation.
The new issue is now:

```
ERROR in node_modules/chartjs-plugin-zoom/types/index.d.ts:16:5 - error TS7010: 'pan', which lacks return-type annotation, implicitly has an 'any' return type.
    
    16     pan(pan: PanAmount, options?: Partial<PanOptions>, scales?: Scale[]);
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    node_modules/chartjs-plugin-zoom/types/index.d.ts:17:5 - error TS7010: 'zoom', which lacks return-type annotation, implicitly has an 'any' return type.
    
    17     zoom(zoom: ZoomAmount, options?: Partial<ZoomOptions>, useTransition?: boolean);
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    node_modules/chartjs-plugin-zoom/types/index.d.ts:25:17 - error TS7010: 'doPan', which lacks return-type annotation, implicitly has an 'any' return type.
    
    25 export function doPan(chart: Chart, pan: PanAmount, options?: Partial<PanOptions>, scales?: Scale[]);
                       ~~~~~
    node_modules/chartjs-plugin-zoom/types/index.d.ts:26:17 - error TS7010: 'doZoom', which lacks return-type annotation, implicitly has an 'any' return type.
    
    26 export function doZoom(chart: Chart, zoom: ZoomAmount, options?: Partial<ZoomOptions>, useTransition?: boolean);
                       ~~~~~~
    node_modules/chartjs-plugin-zoom/types/index.d.ts:27:17 - error TS7010: 'resetZoom', which lacks return-type annotation, implicitly has an 'any' return type.
    
    27 export function resetZoom(chart: Chart);
                       ~~~~~~~~~
```

**Comment by hardmaster92** [comment]
> 
> 
> I'm OK for the import as it is now specified in documentation.
> 
> I still update this issue thread with new error encountered when using the beta.2 and importing the plugin without any ts-ignore and strict validation.
> The new issue is now:
> 
> ```
> ERROR in node_modules/chartjs-plugin-zoom/types/index.d.ts:16:5 - error TS7010: 'pan', which lacks return-type annotation, implicitly has an 'any' return type.
>     
>     16     pan(pan: PanAmount, options?: Partial<PanOptions>, scales?: Scale[]);
>            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     node_modules/chartjs-plugin-zoom/types/index.d.ts:17:5 - error TS7010: 'zoom', which lacks return-type annotation, implicitly has an 'any' return type.
>     
>     17     zoom(zoom: ZoomAmount, options?: Partial<ZoomOptions>, useTransition?: boolean);
>            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     node_modules/chartjs-plugin-zoom/types/index.d.ts:25:17 - error TS7010: 'doPan', which lacks return-type annotation, implicitly has an 'any' return type.
>     
>     25 export function doPan(chart: Chart, pan: PanAmount, options?: Partial<PanOptions>, scales?: Scale[]);
>                        ~~~~~
>     node_modules/chartjs-plugin-zoom/types/index.d.ts:26:17 - error TS7010: 'doZoom', which lacks return-type annotation, implicitly has an 'any' return type.
>     
>     26 export function doZoom(chart: Chart, zoom: ZoomAmount, options?: Partial<ZoomOptions>, useTransition?: boolean);
>                        ~~~~~~
>     node_modules/chartjs-plugin-zoom/types/index.d.ts:27:17 - error TS7010: 'resetZoom', which lacks return-type annotation, implicitly has an 'any' return type.
>     
>     27 export function resetZoom(chart: Chart);
>                        ~~~~~~~~~
> ```
> 
> For the moment, I'm forced to either remove the strict check or set "skipLibCheck": true in my tsconfig.

I already posted about this issue and even there was a PR merged to the master. I think you can expect a new beta soon with this fix ;)

**Comment by kurkle** [comment]
beta.3 is now available in [npm](https://www.npmjs.com/package/chartjs-plugin-zoom/v/1.0.0-beta.3). There are breaking changes on how ranges are configured from https://github.com/chartjs/chartjs-plugin-zoom/pull/470

**Comment by kurkle** [comment]
You can see the new `limits` in action in the basic sample: https://www.chartjs.org/chartjs-plugin-zoom/samples/basic.html (Zoom tab)

**Comment by Nico-DF** [comment]
@hardmaster92 Many thanks for letting me know, great job!

@kurkle Thanks for keeping me updated. I'll close this issue as it does not make any sense anymore and don't want to clobber it.
If I encounter something else, I'll do another proper issue
